spring.application.name=user-service
server.port=8081

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

